language: android

jdk:
  - oraclejdk8

install:
# Let's use the new command 'sdkmanager' to install Android SDK components
- yes | sdkmanager "build-tools;28.0.3"
- yes | sdkmanager "platform-tools"
- yes | sdkmanager "tools"
- yes | sdkmanager "platforms;android-28"
- yes | sdkmanager "system-images;android-28;default;x86"

script:
- ./gradlew clean build -w
