language: android

jdk:
  - oraclejdk8

install:
# Let's use the new command 'sdkmanager' to install Android SDK components
- yes | sdkmanager --verbose "build-tools;28.0.2"
- yes | sdkmanager --verbose "platform-tools"
- yes | sdkmanager --verbose "tools"
- yes | sdkmanager --verbose "platforms;android-28"
- yes | sdkmanager --verbose "system-images;android-28;default;armeabi-v7a"

# Check tools and dependencies installed
- yes | sdkmanager --list

script:
- ./gradlew clean build
